SELECT  FIRST_NAME || ' '  || LAST_NAME AS "NAME", HIRE_DATE , JOB_ID FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG' AND SALARY < 6000;

SELECT FIRST_NAME || ' ' || LAST_NAME AS "NAME",DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (50,80) AND SALARY > 3000 AND FIRST_NAME LIKE 'S%';

SELECT FIRST_NAME || ' ' || LAST_NAME AS "NAME", JOB_ID, PHONE_NUMBER,HIRE_DATE FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG' AND PHONE_NUMBER LIKE '5%' AND HIRE_DATE BETWEEN '01-01-2007' AND '31-12-2007';