SELECT FIRST_NAME,SALARY AS "BRUTO",SALARY * 0.20 AS "IMPUESTOS",SALARY - (SALARY * 0.20) AS "NETO" FROM EMPLOYEES;

SELECT FIRST_NAME || ' ' ||  LAST_NAME AS "NOMBRE",SALARY as "SALARIO",SALARY * 14 AS "PAGO ANUAL" FROM EMPLOYEES; 