--CONCAT

SELECT FIRST_NAME || ' ' || LAST_NAME AS "NAME" 
FROM EMPLOYEES 
ORDER BY NAME ASC 
FETCH FIRST 10 ROWS ONLY;

SELECT CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME) AS "CONCAT NAME" FROM EMPLOYEES;