-- EL WHERE DE LOS GROUP BY : EL HAVING. CONDICIONES SOBRE EL GRUPO
SELECT DEPARTMENT_ID,JOB_ID, COUNT(*),SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID,JOB_ID
HAVING SUM(SALARY) > 25000 AND COUNT(*) > 10
ORDER BY DEPARTMENT_ID;


SELECT * FROM EMPLOYEES;
