SELECT FIRST_NAME, SALARY FROM EMPLOYEES FETCH FIRST 10 ROWS ONLY;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%'
ORDER BY SALARY DESC    
FETCH FIRST 10 ROWS ONLY;


SELECT FIRST_NAME, SALARY FROM EMPLOYEES
ORDER BY SALARY DESC    
FETCH FIRST 7 ROWS WITH TIES;


SELECT * FROM EMPLOYEES FETCH FIRST 20 PERCENT ROWS ONLY;