--ME PERMITE RECUPERAR UN CONJUNTO DE FILAS

 SELECT DEPARTMENT_ID,COUNT(*),SUM(SALARY),AVG(SALARY)
 FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
 ORDER BY DEPARTMENT_ID;

 SELECT DEPARTMENT_ID,COUNT(*)
 FROM EMPLOYEES
 WHERE SALARY >= 3000
 GROUP BY DEPARTMENT_ID
 ORDER BY DEPARTMENT_ID;



