/*
Condiciones complejas usando AND OR Y NOT
*/

SELECT * FROM EMPLOYEES WHERE SALARY >5000 AND DEPARTMENT_ID = 50;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN (50,60);

SELECT FIRST_NAME || ' ' ||LAST_NAME AS "NAME", SALARY, DEPARTMENT_ID,HIRE_DATE FROM EMPLOYEES
WHERE SALARY > 5000 AND DEPARTMENT_ID = 50 AND HIRE_DATE > '01-01-05';

SELECT FIRST_NAME || ' ' ||LAST_NAME AS "NAME", SALARY, DEPARTMENT_ID,HIRE_DATE FROM EMPLOYEES
WHERE SALARY > 5000 AND DEPARTMENT_ID = 50 OR HIRE_DATE > '01-01-05';