--ORACLE MANEJA DOS TIPOS DE CONVERSIONES : IMPLICITAS Y EXPLICITAS
--TO_CHAR, TO_DATE. TO_NUMBER

SELECT '10' + 10 FROM DUAL;
SELECT TO_DATE('10-10-18') + 1 FROM DUAL;
SELECT MONTHS_BETWEEN(SYSDATE,'10-10-18') FROM DUAL;
SELECT 10||'01' FROM DUAL;
SELECT 'HOY ES : ' || SYSDATE FROM DUAL; 

-- TO_CHAR(DATE/NUMBER, 'FORMAT')
--TO_CHAR(DATE,'')
/*
YYYY
YEAR
MM
MONTH
MON
DY
DAY
DD

*/

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YEAR-MONTH-DAY') FROM DUAL;
