--Notas sobre distinct
SELECT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES;
SELECT COUNT(DISTINCT DEPARTMENT_ID) AS "CANTIDAD DE  DEPARTAMENTOS" FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES ORDER BY DEPARTMENT_ID;

--Comentarios de una sola linea
/*

Comentario de varias lineas

*/
