--SUBSTR(CADENA,INICIO,TAMAÑO)
SELECT FIRST_NAME,SUBSTR(FIRST_NAME,1,3) AS "PREFIX" FROM EMPLOYEES;

--INSTR(CADENA1,CADENA2)
SELECT FIRST_NAME,INSTR(FIRST_NAME,'t',2) AS "POSITION IN TEXT" FROM EMPLOYEES WHERE INSTR(FIRST_NAME,'t',2) = 2;
