-- nvl : me permite trabajar con nulos
SELECT FIRST_NAME, COMMISSION_PCT,SALARY ,NVL(COMMISSION_PCT,0) * SALARY FROM EMPLOYEES;

--NVL2 : NVL2(EXPRESION,1,2)
SELECT (FIRST_NAME),COMMISSION_PCT,SALARY,NVL2(COMMISSION_PCT,COMMISSION_PCT * SALARY,0) FROM EMPLOYEES;

--NULLIF(V1,V2)
SELECT NULLIF(1,1) FROM DUAL; 

SELECT COUNTRY_ID,UPPER(SUBSTR(COUNTRY_NAME,1,2)),NVL2(NULLIF(COUNTRY_ID,UPPER(SUBSTR(COUNTRY_NAME,1,2))),'NO IGUALES','IGUALES') AS "MATCH" FROM COUNTRIES;

--COALESCE
SELECT COALESCE(NULL,NULL,5,4) FROM DUAL;

SELECT FIRST_NAME,COALESCE(TO_CHAR(COMMISSION_PCT),TO_CHAR(MANAGER_ID),'SIN JEFE NI COMISION') FROM EMPLOYEES;
