--FUNCION DE CARACTERES LENGTH
SELECT FIRST_NAME, LENGTH(FIRST_NAME) as "LENGTH" FROM EMPLOYEES;

--CUANTOS EMPLEADOS TIENEN UN NOMBRE MAYOR A 6 CARACTERES
SELECT FIRST_NAME, LENGTH(FIRST_NAME) AS "LENGTH" FROM EMPLOYEES WHERE LENGTH(FIRST_NAME) > 6 ORDER BY FIRST_NAME;