--COMANDO ROUN, PERMITE REDONDEAR UN CANTIDAD
--ROUN(CANTIDAD,CANTIDAD DE REDONDEO)

SET serveroutput ON;

DECLARE
    v_numero number;
BEGIN
    v_numero := 50.2132;
    DBMS_OUTPUT.PUT_LINE('EL VALOR ES : ' || TO_CHAR(v_numero));
    DBMS_OUTPUT.PUT_LINE('EL VALOR ES :' || TO_CHAR(ROUND(v_numero,3)));
END;


SELECT ROUND(45.678,1) FROM DUAL;

SELECT TRUNC(34.39562,2) FROM DUAL;

SELECT MOD(10,3) FROM DUAL;