-- CASE
/*
VALOR 1
    CASE 10
    CASE 20
    ...
*/

SELECT * FROM EMPLOYEES;
SELECT FIRST_NAME, JOB_ID, 
CASE JOB_ID
    WHEN 'SH_CLERK' THEN 'TIPO 1'
    WHEN 'ST_MAN' THEN 'TIPO 2'
    WHEN 'ST_CLERK' THEN 'TIPO 3'
    ELSE 'OTRO'
END
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;


/*
CASE SEARCHED
*/
SELECT FIRST_NAME,SALARY,
    CASE WHEN SALARY BETWEEN 0 AND 3000 THEN 'LOW' 
        WHEN SALARY BETWEEN 3001 AND 5000 THEN 'MEDIUM'
        WHEN SALARY > 5001 THEN 'GANAS BIEN'
        ELSE 'NO APLICABLE'
    END
FROM EMPLOYEES;


/*
SENTENCIA DECODE
DECODE(VALOR,CONDICION1,V1,CONDICION2,VALORS2...VALOR FINAL)
*/

SELECT FIRST_NAME,DEPARTMENT_ID,DECODE(DEPARTMENT_ID,50,'INFORMATICA',60,'HR',90,'CONTABILIDAD','NO DATA FOUND') 
FROM EMPLOYEES;
