--MONTHS_BETWEEN  - PERMITE SABER EL NUMERO DE MESES ENTRE DOS FECHAS...
--ADD_MONTHS - PERMITE AÑADIR MESES A UNA FECHA
--NEXT_DAY - ESPERA UNA FECHA  Y UNA CADENA
--LAST_DAY - REGRESA LA ULTIMA FECHA DE ESE MES
--ROUND Y TRUNC - REDONDEAR EN EL AMBITO DE FECHAS



SELECT MONTHS_BETWEEN('31/12/2026','20/07/2026') FROM DUAL;
SELECT HIRE_DATE, SYSDATE ,TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE),2) AS "MESES TRABAJANDO" FROM EMPLOYEES;
SELECT ADD_MONTHS('12/05/2026',3) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,6) FROM DUAL;
SELECT NEXT_DAY('20/07/2026','Wednesday') FROM DUAL;
SELECT LAST_DAY('11/02/2026') FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;
SELECT ROUND(SYSDATE,'MONTH') FROM DUAL;
SELECT ROUND(TO_DATE('12/07/2026', 'DD/MM/YYYY'), 'MONTH') FROM DUAL;
SELECT TRUNC(SYSDATE,'MONTH') FROM DUAL;
SELECT ROUND(SYSDATE,'YEAR') FROM DUAL;
SELECT TRUNC(SYSDATE,'YEAR') FROM DUAL;
SELECT ROUND(SYSDATE,'MONTH') FROM DUAL;