--LOWER
--UPPER
--INITCAP
SELECT UPPER(FIRST_NAME) || ' ' || UPPER(LAST_NAME) AS "NAME", LOWER(EMAIL) as "EMAIL" FROM EMPLOYEES;
SELECT UPPER(FIRST_NAME) || ' ' || UPPER(LAST_NAME) AS "NAME", INITCAP(EMAIL) as "EMAIL" FROM EMPLOYEES;