SELECT MAX(SALARY) as "MAX SALARY" FROM EMPLOYEES;

SELECT TRUNC(AVG(SALARY),3),DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT MAX(SALARY),DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT MAX(SALARY), MIN(SALARY),TRUNC(AVG(SALARY))
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;


SELECT MIN(FIRST_NAME) FROM EMPLOYEES;

SELECT MIN(HIRE_DATE),MAX(HIRE_DATE) FROM EMPLOYEES;

--FUNCION DE GRUPO COUNT (CUENTA TODO MENOS LOS NULL)
SELECT COUNT(FIRST_NAME) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;

SELECT COUNT(COMMISSION_PCT) FROM EMPLOYEES;

SELECT COUNT(SALARY),COUNT(COMMISSION_PCT) FROM EMPLOYEES;

SELECT COUNT(*) FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

SELECT COUNT(*) FROM EMPLOYEES
WHERE SALARY > 6000;

SELECT COUNT(DISTINCT(FIRST_NAME)) FROM EMPLOYEES;

SELECT COUNT(DISTINCT(DEPARTMENT_ID)) FROM EMPLOYEES;

--FUNCION SUM
SELECT SUM(SALARY) FROM EMPLOYEES;

SELECT SUM(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;

SELECT SUM(SALARY)/COUNT(*) FROM EMPLOYEES;
SELECT AVG(SALARY) FROM EMPLOYEES;