SELECT MAX(SALARY) as "MAX SALARY" FROM EMPLOYEES;

SELECT TRUNC(AVG(SALARY),3),DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT MAX(SALARY),DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT MAX(SALARY), MIN(SALARY),TRUNC(AVG(SALARY))
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;


SELECT MIN(FIRST_NAME) FROM EMPLOYEES;

SELECT MIN(HIRE_DATE),MAX(HIRE_DATE) FROM EMPLOYEES;