-- LPAD
-- RPAD
SELECT FIRST_NAME FROM EMPLOYEES;
SELECT FIRST_NAME, RPAD(FIRST_NAME,10,'*') FROM EMPLOYEES;
SELECT FIRST_NAME, LPAD(FIRST_NAME,10,'-') FROM EMPLOYEES;

-- REPLACE
-- LTRIM
-- RTRIM
SELECT FIRST_NAME, REPLACE(FIRST_NAME,'a','x') AS "CAMBIO" FROM EMPLOYEES;

   
SELECT '                Hola    ' || ' adios. ' AS "MENSAGE" FROM DUAL;
SELECT LTRIM(RTRIM(' Hola    ' || ' adios. ')) AS "MENSAGE" FROM DUAL;


SELECT FIRST_NAME, RTRIM(FIRST_NAME,'n')FROM EMPLOYEES;
