/*
suma, resta , multiplicacion, division, modulo
*/

SELECT FIRST_NAME, SALARY, SALARY * 12 AS "SALARIO ANUAL", SALARY * .16 AS "IMPUESTO MENSUAL", SALARY - (SALARY*0.16) AS "SALARIO REAL MENSUAL" FROM EMPLOYEES;