SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE DESC;

--  SI HAY COINCIDENCIAS EN DATOS EN LA PRIMER COULMA ORDENA APOR LA SEGUNDA (LAST_NAME)
SELECT * FROM EMPLOYEES ORDER BY FIRST_NAME,LAST_NAME;
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'David' ORDER BY FIRST_NAME,LAST_NAME;

SELECT FIRST_NAME || ' ' || LAST_NAME AS "NAME", SALARY - SALARY * 0.16 AS "REAL SALARY" FROM EMPLOYEES ORDER BY "REAL SALARY"; 