SELECT E.EMPLOYEE_ID,E.FIRST_NAME,D.DEPARTMENT_NAME  FROM 
EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--NATURAL JOIN...(junta por columnas que se llaman igual)
SELECT C.COUNTRY_NAME,R.REGION_NAME
FROM COUNTRIES C
JOIN REGIONS R
ON C.REGION_ID = R.REGION_ID;


--SOLAMENTE CUANDO LAS COLUMNAS SEAN UNICAS E IGUALES
SELECT * 
FROM COUNTRIES
NATURAL JOIN
REGIONS;

--USO DE CLAUSULA USING. LE INDFICAMOS CUAL COLUMNA USAR
SELECT D.DEPARTMENT_NAME,E.FIRST_NAME,E.SALARY 
FROM EMPLOYEES E JOIN DEPARTMENTS D
    USING (DEPARTMENT_ID)
WHERE SALARY > 5000;

--clausula on. es parecido a usign, pero 
SELECT D.DEPARTMENT_NAME, E.FIRST_NAME,E.SALARY
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON (D.DEPARTMENT_ID = E.DEPARTMENT_ID);



SELECT E.FIRST_NAME || ' ' || LAST_NAME AS "NAME",E.DEPARTMENT_ID,D.DEPARTMENT_ID, D.DEPARTMENT_NAME,D.LOCATION_ID,LOC.LOCATION_ID,LOC.CITY
FROM EMPLOYEES E
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS LOC 
ON D.LOCATION_ID = LOC.LOCATION_ID
AND  E.SALARY > 6000;