SELECT E.EMPLOYEE_ID,E.FIRST_NAME,D.DEPARTMENT_NAME  FROM 
EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--NATURAL JOIN...(junta por columnas que se llaman igual)
SELECT C.COUNTRY_NAME,R.REGION_NAME
FROM COUNTRIES C
JOIN REGIONS R
ON C.REGION_ID = R.REGION_ID;

SELECT * 
FROM COUNTRIES
NATURAL JOIN
REGIONS;
